"use client";
import { Download } from "lucide-react";
import { Button } from "../ui/button";
import jsPDF from "jspdf";
export function DownloadSummaryButton({
  title,
  summaryText,
  fileName,
  createdAt,
}: {
  title: string;
  summaryText: string;
  fileName: string;
  createdAt: string;
}) {
  const handleDownload = () => {
    const doc = new jsPDF({
      orientation: "portrait",
      unit: "mm",
      format: "a4",
    });

    // Set up colors and fonts
    const primaryColor = [79, 70, 229]; // Indigo
    const textColor = [31, 41, 55]; // Gray-800
    const lightGray = [156, 163, 175]; // Gray-400

    let yPosition = 25;
    const pageWidth = doc.internal.pageSize.getWidth();
    const margins = { left: 20, right: 20 };
    const contentWidth = pageWidth - margins.left - margins.right;

    // Header with gradient effect (simulated with rectangle)
    doc.setFillColor(79, 70, 229);
    doc.rect(0, 0, pageWidth, 35, "F");

    // Title
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(24);
    doc.setFont("helvetica", "bold");
    const titleLines = doc.splitTextToSize(title, contentWidth - 40);
    doc.text(titleLines, margins.left + 20, yPosition);
    yPosition += titleLines.length * 8;

    // Subtitle
    doc.setFontSize(14);
    doc.setFont("helvetica", "normal");
    doc.text("AI-Generated Document Summary", margins.left + 20, yPosition);
    yPosition = 50;

    // Document info section
    // doc.setTextColor(...textColor);
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text("Document Information", margins.left, yPosition);
    yPosition += 10;

    // Info details
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    // doc.setTextColor(...lightGray);

    const infoItems = [
      `Generated on: ${new Date(createdAt).toLocaleDateString("en-US", {
        year: "numeric",
        month: "long",
        day: "numeric",
        hour: "2-digit",
        minute: "2-digit",
      })}`,
      `Original file: ${fileName}`,
      `Generated by: DocChat.ai`,
    ];

    infoItems.forEach((item) => {
      doc.text(item, margins.left, yPosition);
      yPosition += 6;
    });

    yPosition += 10;

    // Divider line
    // doc.setDrawColor(...lightGray);
    doc.setLineWidth(0.5);
    doc.line(margins.left, yPosition, pageWidth - margins.right, yPosition);
    yPosition += 15;

    // Summary content
    // doc.setTextColor(...textColor);
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text("Summary", margins.left, yPosition);
    yPosition += 12;

    // Summary text with proper wrapping
    doc.setFontSize(11);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(55, 65, 81); // Gray-700

    const summaryLines = doc.splitTextToSize(summaryText, contentWidth);

    summaryLines.forEach((line: string) => {
      // Check if we need a new page
      if (yPosition > 260) {
        doc.addPage();
        yPosition = 25;
      }
      doc.text(line, margins.left, yPosition);
      yPosition += 6;
    });

    // Footer
    const pageCount = doc.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);

      // Footer line
      //   doc.setDrawColor(...lightGray);
      doc.line(margins.left, 280, pageWidth - margins.right, 280);

      // Footer text
      doc.setFontSize(8);
      //   doc.setTextColor(...lightGray);
      doc.text(
        `Generated by DocChat.ai | Page ${i} of ${pageCount}`,
        margins.left,
        285
      );

      doc.text(
        new Date().toLocaleDateString(),
        pageWidth - margins.right - 30,
        285
      );
    }

    // Download the PDF
    doc.save(
      `${title.replace(/[^a-z0-9\s]/gi, "").replace(/\s+/g, "_")}_Summary.pdf`
    );
  };
  return (
    <Button
      size="sm"
      className="h-8 px-4 text-white bg-indigo-500 hover:bg-white hover:text-indigo-600 transition-colors duration-300 ease-in-out border border-transparent hover:border-indigo-500 shadow-sm hover:shadow-md"
      onClick={handleDownload}
    >
      <Download className="h-4 w-4 mr-1" />
      Download Summary
    </Button>
  );
}
